"""S0 UI port. Implementations must enforce authorization and transactions.

No service implementation or approval persistence is claimed by this Protocol.
"""
from typing import Protocol, runtime_checkable
from .schemas import (ActorContext, Confirmation, DecisionInput, DocumentBundle,
    ListQuery, ProductEvidence, PurchaseRequest, RequestDetail, RequestInput,
    RequestPage, RequestPatch, RequestRef, ReviewResult, ToolResult)

@runtime_checkable
class PurchaseService(Protocol):
    def list_requests(self, context: ActorContext, query: ListQuery) -> ToolResult[RequestPage]: ...
    def get_request(self, context: ActorContext, ref: RequestRef) -> ToolResult[RequestDetail]: ...
    def get_latest_request(self, context: ActorContext, request_id: str) -> ToolResult[RequestDetail]: ...
    def create_request(self, context: ActorContext, inputs: RequestInput, action_id: str) -> ToolResult[PurchaseRequest]: ...
    def update_request(self, context: ActorContext, request_id: str, patch: RequestPatch) -> ToolResult[PurchaseRequest]: ...
    def search_products(self, context: ActorContext, ref: RequestRef, keyword: str, limit: int = 5, refresh: bool = False) -> ToolResult[list[ProductEvidence]]: ...
    def review_request(self, context: ActorContext, ref: RequestRef) -> ToolResult[ReviewResult]: ...
    def generate_documents(self, context: ActorContext, ref: RequestRef) -> ToolResult[DocumentBundle]: ...
    def prepare_submission(self, context: ActorContext, ref: RequestRef, bundle_id: str) -> ToolResult[Confirmation]: ...
    def submit_request(self, context: ActorContext, confirmation: Confirmation) -> ToolResult[PurchaseRequest]: ...
    def decide(self, context: ActorContext, decision: DecisionInput) -> ToolResult[PurchaseRequest]: ...
    def download_document(self, context: ActorContext, ref: RequestRef, kind: str) -> ToolResult[bytes]: ...
